const quotes = [
    "Are non-dads allowed to make dad jokes? Or is it a \"faux pa\"",
    "You hear a knock at the door. You open it. No one is there. It's just a faucet with a basin. Let that sink in.",
    "Yoshi invited me to a party and I asked what he wanted me to bring. I offered beer, but he said... brrrring POP!",
    "You know what Yoda said when he saw himself in 1080p for the first time? HD M I",
    "I was kidnapped by a group of mimes and they did unspeakable things!",
    "There's a fine line between a numerator and a denominator.",
    "Thank you for spending the time to teach me the meaning of \"many\". It means a lot.",
    "I have found that you can't trust atoms. They make up everything!",
    "I am reading a novel in braille. Something bad is going to happen - I can feel it. ",
    "My friend's wife gave birth in the car on the way to the hospital! They named him \"Carson\"",
    "Please make sure you uninstall 2020 and install it fresh. There's a nasty virus in the current version!",
    "Fun fact: The least spoken language in the world is sign language.",
    "I can\u2019t believe someone broke into my garage and stole my limbo stick. Seriously, how low can you go?",
    "I need to figure out how to stop procrastinating. I'll do that later though.",
    "I was going to get a 6 pack of Sprite at the grocery store, but I accidentally picked 7-up",
    "I never wanted a beard, but it's growing on me.",
    "A man tried to sell me a coffin today. I told him that's the last thing I need.",
    "I just found out something that's odd. It's a number not divisible by 2.",
    "My friend keeps saying \"cheer up man it could be worse, you could be stuck underground in a hole full of water.\" I know he means well.",
    "My friend told me I have no sense of direction. I packed up my stuff and right. ",
    "Yeah this year sucks, but 2022 will suck too. Because 2022 is 2020, too. ",
    "My friend got fired from the calendar printing company for taking a month off... :( ",
    "That was the most emotional wedding ever. Even the cake was in tiers!",
    "I heard the guy who won the ski race was actually on a sled... but they let it slide!",
    "That's a nice ham you got there. It'd be a shame if you put an 's' on one end and an 'e' on the other.",
    "I recently developed a severe fear of elevators. I'm taking the steps to avoid them.",
    "I never wanted to believe that my dad was stealing from his job as a road worker, but when I got home, all the signs were there.",
    "I had a dream last night that I was a muffler... I woke up exhausted!",
    "I just learned about a 12 inch tall king. He was a terrible leader... but he made a great ruler!",
    "Nothing tops a plain pizza! <<THIS ONE FAILED>>",
    "Water is lighter than butane. After all, butane is a lighter fluid.",
    "The Lego store just reopened after closing during lockdown. People are lined up for blocks!",
    "I keep asking my friend what LGBTQ means, but I can't get a straight answer.",
    "My printer kept playing music, turned out the paper was jamming.",
    "I can't figure out why someone would steal my weight loss pills. They have nothing to gain!",
    "I quit my job as a treadmill tester. It just felt like I wasn\u2019t going anywhere...",
    "I tried to organize a professional hide and seek tournament, but it was a complete failure. Good players are hard to find.",
    "The guy who stole my diary died yesterday. My thoughts are with his family.",
    "I was going to share my joke about paper, but it's tearable. ",
    "Do you know why you can't run through a campsite? You can only 'ran', it's past tents.",
    "My Internet service provider has no data limits. No cap.",
    "To the person who cut me in line at the grocery store: I'm after you now.",
    "If you rearrange the letters of \"a postal worker\"... they get really pissed off.",
    "eBay is so useless. I tried to look up lighters and all they had was 13,749 matches.",
    "Did you hear the CEO of IKEA became the Prime Minister of Sweden? He's been busy assembling his new cabinet.",
    "A new species of head lice is going around and it's resistant to treatment! That has left scientists scratching their heads.",
    "I wrote down my enemies on paper, and my friend used the paper to roll a joint. He\u2019s now high on the list of people I hate.",
    "I like a lot of things about Switzerland, and the flag is a big plus!",
    "I only took 10 minutes to walk to the bar, but it took me a whole hour to walk home. The difference is staggering.",
    "They've invented a thought-controlled air freshener. It makes scents when you think about it!",
    "I got arrested for downloading all of Wikipedia. When I was taken into custody, I told them I could explain everything.",
    "I have a friend that's a kleptomaniac. When it gets really bad he takes something for it.",
    "The inventor of the Ferris wheel and the inventor of merry-go-round never met. Seems they traveled in different circles.",
    "Hey everyone! I invented a new word: plagiarism.",
    "My little cousin asked \"What rhymes with orange?\" I thought about it for a while and finally said \"No, it doesn't!\"",
    "I paid a ton for a limo and just found out it doesn't include a driver. I spent all that money and have nothing to chauffer it!",
    "The doctor told me my DNA was backwards... I said: \"AND?\"",
    "I bought a book called Binary 101. I thought it would be simple but it seems like it started 5 books in!",
    "Earlier, my friend asked me to hand her the lipstick. I accidentally gave her a glue stick. She still isn't talking to me.",
    "I call the new guy at work \"the computer.\" It's not that he's smart, rather he sleeps if left unattended for 15 minutes.",
    "I watched a documentary about how ships are made. It was riveting! ",
    "I spent the whole morning building a time machine, so that\u2019s four hours of my life that I\u2019m definitely getting back.",
    "Did you know if you get pregnant in the Amazon, it\u2019s next day delivery?",
    "I had an idea for a funny Discord status but I tried to write it down and my pencil broke. Now it's pointless.",
    "I asked my favorite Indian restaurant for their secret flatbread recipe. I had to sign a naan disclosure agreement.",
    "How do you wear a ship as a hat? Easy. Turn it upside down so it's capsized. ",
    "I heard my coworkers making fun of someone with bad posture. I have a hunch it might be me.",
    "I talked to a customer at a helium plant. I wont take their calls again. I won't be talked to in that tone.",
    "I saw someone fall on his driveway today. He was screaming in pain and blaming his kids. It was his own asphalt!",
    "I just bought a set of speakers for $1!! They were cheap because the volume is stuck at the max. I couldn't turn them down!",
    "Went to a wedding where two slices of bread got married! It all went well until someone decided to toast the bride and groom...",
    "I had to tell my suitcase my trip was canceled and it won't stop crying. Emotional baggage is the worst.",
    "My psychiatrist once said I was paranoid. Well, he didn't actually say it, but I could tell he was thinking it.",
    "You should try archery with a blindfold. You don't know what you're missing!",
    "People are usually shocked when they find out I'm not a very good electrician.",
    "I recently confused the words \"jacuzzi\" and \"yakuza\". Now I'm in hot water with the Japanese mafia.",
    "I hate funerals. I\u2019m just not a mourning person.",
    "I don't trust magazine collectors. They have too many issues.",
    "Did you hear about the actor that fell through the floor boards last night? It was just a stage he was going through...",
    "Will glass coffins ever be popular? Remains to be seen.",
    "If you're going to start a zoo, you need one grizzly, two pandas, and a polar bear. That is the bear minimum for any zoo.",
    "I was studying to be a financial advisor but it wasn't going well. I lost interest.",
    "My mom called to warn me that someone was driving the wrong way on the highway I was on. It wasn't one person - it was everyone!",
    "I'm considering a new line of work that I can really see myself doing. I want to be a mirror inspector!",
];

const quoteEl = document.getElementById("quote");
const timeEl = document.getElementById("now");
const rerollQuote = () => {
    quoteEl.innerText = quotes[Math.floor(quotes.length * Math.random())];

    const now = new Date();
    timeEl.innerText = `Today at ${now.getHours().toString().padStart(2, "0")}:${now.getMinutes().toString().padStart(2, "0")}`
}

quoteEl.onclick = rerollQuote;
rerollQuote();
